# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='city',
            field=models.CharField(default='default', max_length=120),
        ),
    ]
