# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20181226_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='city',
            field=models.CharField(blank=True, default='default', max_length=120),
        ),
    ]
