# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='mobile_number',
            field=models.TextField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
