# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0001_initial'),
        ('marketplace', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('background_image_a', models.ImageField(null=True, upload_to=store.models.upload_image_path)),
                ('background_image_b', models.ImageField(blank=True, null=True, upload_to=store.models.upload_image_path)),
                ('order', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.Brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=store.models.upload_image_path)),
                ('description', models.TextField(blank=True)),
                ('ordering', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('extra_description', models.TextField(blank=True, help_text='Additional Information, Care tips?')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('image_a', models.ImageField(help_text='First image displayed to customers', upload_to=store.models.upload_image_path)),
                ('image_b', models.ImageField(help_text='Second image displayed to customers', upload_to=store.models.upload_image_path)),
                ('image_c', models.ImageField(help_text='Third image displayed to customers', upload_to=store.models.upload_image_path)),
                ('has_variants', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('new_in', models.BooleanField(default=False)),
                ('on_sale', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('discount', models.PositiveIntegerField(blank=True, choices=[(0, '0'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55')], help_text="Percentage '%' discount", null=True)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Overwritten if variants', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.Category')),
                ('product_type', models.ForeignKey(default=0.7, help_text='For calculating shipping cost', null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.ProductWeight')),
                ('store', mptt.fields.TreeForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.Store')),
                ('tags', models.ManyToManyField(related_name='products', to='tags.Tag')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='First image displayed to customers', null=True, upload_to=store.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter product review here.', max_length=600)),
                ('is_active', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('W-30', 'W-30'), ('W-32', 'W-32'), ('W-34', 'W-34'), ('W-36', 'W-36')], help_text='select a size.', max_length=120)),
                ('quantity', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25')], null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'ordering': ['product', '-size'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set([('product', 'size')]),
        ),
    ]
