# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-21 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
