# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-29 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20181221_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='00000', max_length=120, unique=True),
        ),
    ]
