# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-29 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
