# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import marketplace.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('seller_type', models.CharField(choices=[('brand', 'Brand'), ('outlet', 'Outlet')], max_length=120)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('twitter', models.CharField(blank=True, max_length=120)),
                ('whatsapp', models.CharField(blank=True, max_length=120)),
                ('background_image_a', models.ImageField(blank=True, help_text='Used if STORE is featured on the Marketplace', null=True, upload_to=marketplace.models.upload_image_path)),
                ('background_image_b', models.ImageField(null=True, upload_to=marketplace.models.upload_image_path)),
                ('ordering', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='marketplace.Store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
