# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import marketplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20181114_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='background_image_a',
        ),
        migrations.RemoveField(
            model_name='store',
            name='background_image_b',
        ),
        migrations.AddField(
            model_name='store',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='store',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to=marketplace.models.upload_image_path),
        ),
    ]
