# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20181219_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shipping_covered',
            field=models.BooleanField(default=False),
        ),
    ]
