# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('W-28', 'W-28'), ('W-30', 'W-30'), ('W-32', 'W-32'), ('W-34', 'W-34'), ('W-36', 'W-36'), ('W-38', 'W-38')], max_length=120),
        ),
    ]
