# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-14 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20181114_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordering']},
        ),
    ]
