# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-10 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20181114_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='platform',
            field=models.CharField(choices=[('store', 'Store'), ('marketplace', 'Marketplace')], default='store', max_length=120),
        ),
    ]
