# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('percentage', models.PositiveIntegerField(blank=True, choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (65, '65'), (70, '70'), (75, '75')])),
                ('amount', models.IntegerField(blank=True)),
                ('usage', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('first_order_coupon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsedCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.CouponCode')),
            ],
        ),
    ]
