# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-03 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20181203_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
