# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_usedcoupon_coupon_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='is_one_use_only',
            field=models.BooleanField(default=False),
        ),
    ]
