# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_couponcode_is_one_use_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='is_valid_till',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
