# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20181226_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
