# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-28 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_couponcode_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponcode',
            name='is_active',
        ),
    ]
