# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_couponcode_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
