# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20181230_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (65, '65'), (70, '70'), (75, '75')], null=True),
        ),
    ]
