# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20181230_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
