# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-10 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20190102_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcoupon',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
