# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-03 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.BooleanField(default=False),
        ),
    ]
