# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-04 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_pdf_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
