# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon_code',
            new_name='coupon_applied',
        ),
    ]
