# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20181226_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
